# this file is auto-generated by main.org, do not modify!

inputs: with inputs; { pkgs, ... }: {

  imports = [
    {
      home.packages = [ pkgs.bat ];
    }
    {
      home.packages = [ pkgs.fd ];
    }
    {
      home.packages = [ pkgs.ripgrep ];
    }
  ];

  programs.bash = {
    enable = true;

    initExtra = ''
      alias cat="bat"

      mkcd(){
          mkdir -p -- "$1" && cd -P -- "$1"
      }

      ff(){
        emacsclient $@ &
      }
    '';
  };

  home.packages = [ pkgs.tree pkgs.curl pkgs.htop pkgs.inetutils ];
}
