# this file is auto-generated by main.org, do not modify!

inputs: with inputs; { pkgs, ... }: {
  home.packages = [
    (
      pkgs.stdenv.mkDerivation {
        name = "mdloader";
        src = qmk-firmwork-loader;
        buildFlags = "CC=cc";
        installPhase = ''
          install -Dt $out/bin/ ./build/mdloader
          cp applet-mdflash.bin $out/bin/
        '';
      }
    )
  ];
}
