# this file is auto-generated by main.org, do not modify!

inputs: with inputs; { pkgs, config, ... }: {

  imports = [
    {
      programs.git.delta.enable = true;
    }
  ];

  programs = {
    git = {
      enable = true;

      userName = self.realUser;
      userEmail = "junyi.yi.hou@gmail.com";
      # userEmail =
      #   let
      #     defaultAcc = with builtins; head
      #       (filter (a: a.primary) (attrValues config.accounts.email.accounts));
      #   in
      #     defaultAcc.address;
      aliases = {
        st = "status";
        co = "checkout";
        log = "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit";
      };
      ignores = [
        
      ];
      extraConfig = {
        github = {
          user = "junyi-hou";
        };
      };
    };
  };

  home.packages = [ pkgs.gitAndTools.delta ];
}
