# this file is auto-generated by main.org, do not modify!

inputs: with inputs; { pkgs, ... }: {
  imports = [
    {
      home.packages = with pkgs; [
        aspell aspellDicts.en aspellDicts.en-computers aspellDicts.en-science
      ];
    }
    {
      home.packages = [ pkgs.languagetool ];
    }
  ];
}
