# this file is auto-generated by main.org, do not modify!

inputs: with inputs; homeDirectory: {
  programs.password-store = {
    enable = true;
    settings = {
      PASSWORD_STORE_DIR = "${homeDirectory}/.password-store";
    };
  };
}
