# this file is auto-generated by main.org, do not modify!

{
  description = "Junyi's configuration file";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nix-darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    emacs-overlay.url = "github:nix-community/emacs-overlay";
    emacs-module.url = "path:./emacs.d";
    pragmata-pro = {
      url = "file:///home/junyi/Downloads/PragmataPro0.829.tar.gz";
      flake = false;
    };
    rnix-lsp = {
      url = "github:nix-community/rnix-lsp";
    };
    digestif = {
      url = "github:astoff/digestif";
      flake = false;
    };
    nix-gl = {
      url = "github:guibou/nixGL";
      flake = false;
    };
    qmk-firmwork-loader = {
      url = "github:Massdrop/mdloader";
      flake = false;
    };
  };

  outputs = { self, ... }@inputs: {

    realUser = "Junyi Hou";

    homeModules = let
      moduleDir = ./modules;
      importFn = name: _: import (moduleDir + "/${name}") inputs;
      filterAttrs = inputs.nixpkgs.lib.filterAttrs;
      filterFn = name: _: inputs.nixpkgs.lib.hasSuffix ".nix" name;
    in
      builtins.mapAttrs importFn (filterAttrs filterFn (builtins.readDir moduleDir));

    # ==========================
    # x86_64-linux configuration
    # ==========================

    defaultPackage."x86_64-linux" = self.homeConfigurations."x86_64-linux".activationPackage;
    homeConfigurations."x86_64-linux" = with inputs; home-manager.lib.homeManagerConfiguration rec
      {
        system = "x86_64-linux";
        homeDirectory = "/home/junyi";
        username = "junyi";
        configuration = { pkgs, lib, config, ... }: {
          programs.home-manager.enable = true;
          imports = [
            {
              home = {
                file = {
                  ".config/i3/config".source = ./linux/i3;
                  ".config/dunst/dunstrc".source = ./linux/dunst;
                };
                packages = [
                  pkgs.libnotify
                  pkgs.dunst
                ];
              };
            }
            {
              home.sessionPath = [ "/usr/bin" ];
            }
            (
              let
                pkgs = import nixpkgs { inherit system; overlays = [ emacs-overlay.overlay ]; };
              in
                (emacs-module.emacsPackage pkgs.emacsGcc)
            )
            self.homeModules."git.nix"
            {
              home.packages = [
                pkgs.xdotool
                pkgs.jq
                (pkgs.writeScriptBin "zathuraInverseSearch" ''
                  #!${pkgs.stdenv.shell}
                  focused_window=$(i3-msg -t get_tree | jq -r 'recurse(.nodes[]) | select( .focused == true)')
                  left=$(echo $focused_window | jq .rect.x)
                  top=$(echo $focused_window | jq .rect.y)
                  width=$(echo $focused_window | jq .window_rect.width)
                  height=$(echo $focused_window | jq .window_rect.height)
            
                  # move cursor to (left+width/2, top+height/2)
                  xdotool mousemove $(expr $left + $width / 2) $(expr $top + $height / 2)
            
                  # send ctrl+click
                  xdotool keydown ctrl click 1 keyup ctrl
                '')
              ];
            }
            {
              home.packages = [ pkgs.firefox ];
            }
            (
              let
                nixGL = (import "${nix-gl}" { pkgs = pkgs; }).nixGLIntel;
                wrapped = pkgs.writeScriptBin "alacritty" ''
                  #!${pkgs.stdenv.shell}
                  exec ${nixGL}/bin/nixGLIntel ${nixpkgs.legacyPackages."${system}".alacritty}/bin/alacritty
                '';
              in
              {
                nixpkgs.overlays = [ (final: prev: { alacritty = wrapped; }) ];
              }
            )
            emacs-module.emacsConfig
            self.homeModules."font.nix"
            self.homeModules."grammar.nix"
            {
              home.packages = [ pkgs.delta ];
            }
            self.homeModules."direnv.nix"
            (self.homeModules."nix-development.nix" system)
            self.homeModules."latex.nix"
            self.homeModules."cli.nix"
            self.homeModules."terminal-emulator.nix"
            self.homeModules."drop-keyboard-loader.nix"
            
          ];
        };
      };

    # ===========================
    # x86_64-darwin configuration
    # ===========================

    defaultPackage."x86_64-darwin" = self.homeConfigurations."x86_64-darwin".system;
    packages.x86_64-darwin.darwinConfigurations = let
      hostname = builtins.getEnv "HOSTNAME";
    in {
      "${hostname}" = self.homeConfigurations."x86_64-darwin";
      "junyi-hou--C02FM0MMMD6R" = self.homeConfigurations."x86_64-darwin";
    };

    homeConfigurations."x86_64-darwin" = with inputs;
      let
        system = "x86_64-darwin";
      in
        nix-darwin.lib.darwinSystem rec {
          modules = [
            (
              {pkgs, ...}: {
                nix.package = pkgs.nixUnstable;
                services.nix-daemon.enable = true;
                users.users."junyi.hou".name = "junyi.hou";
                users.users."junyi.hou".home = "/Users/junyi.hou";
              }
            )
            
            (
              let
                pkgs = import nixpkgs { inherit system; overlays = [ emacs-overlay.overlay ]; };
              in {
                imports = [
                  emacs-module.darwinCompatiblePatch
                  (emacs-module.emacsPackage pkgs.emacsGcc)
                ];
              }
            )
            home-manager.darwinModules.home-manager {
              home-manager.useGlobalPkgs = true;
              home-manager.users."junyi.hou" = { pkgs, lib, config, ... }: {
                programs.home-manager.enable = true;
    home.stateVersion = "21.03";
                imports = [
                  emacs-module.emacsConfig
                  self.homeModules."font.nix"
                  self.homeModules."grammar.nix"
                  {
                    home.packages = [ pkgs.delta ];
                  }
                  self.homeModules."direnv.nix"
                  (self.homeModules."nix-development.nix" system)
                  self.homeModules."latex.nix"
                  self.homeModules."cli.nix"
                  self.homeModules."terminal-emulator.nix"
                  self.homeModules."drop-keyboard-loader.nix"
                ];
              };
            }
          ];
        };
  };
}
