* Overview

  This repository contains setup of development environment for doing economic research/data science. I use ~home-manager~ to manage home configuration ("dotfiles"), and ~flake~ to manage dependencies.

** Usage

*** Initialization

Make sure the ~nix~ package manager is available in the current system, and the current user is a trusted user. To make current user trusted, edit ~/etc/nix/nix.conf~ and add
#+begin_src shell
  trusted-users = USER-NAME
#+end_src

To install this configuration, clone this repository and run

  #+begin_src shell
    ./update-user-config
  #+end_src

*** Update Configuration

The script ~update-user-config~ is used to initialize or update configuration. This script does two things. First, it start an new ~emacs~ process in batch mode and tangle ~main.org~, which updates all relevant NixOS modules and user configurations. Second, it runs ~nix build~ to implement those updates. Therefore, the preferred way of updating is to edit ~main.org~ and make changes as see fit, then call ~gatsby:switch-home~ in ~emacs~ or run ~./update-user-config~ in shell to automatically update (tangle) the new setting.

Alternatively, one can manually edit ~*.nix~ and run
#+begin_src shell
  ./update-user-config --no-tangle
#+end_src
to commit updates. The ~--no-tangle~ flag is important: without this flag, ~update-user-config~ will restore the ~*.nix~ files and there will be no update made.

** Repository Structure

+ project-root
  - main.org        -- the org file that generates all configuration
  - emacs.d         -- ~emacs~ configuration file
  - modules         -- nixOS modules generated from ~main.org~
  - linux           -- linux-specific configuration files
  - darwin          -- macOS-specific configuration files

** News

*** 2021-05-18 Tue

- disable vterm module due to a nix-specific [[https://github.com/akermu/emacs-libvterm/issues/333#issuecomment-824172389][bug]] reported here.
- use a different branch for org-appear which supports ~feature/org-fold~
- fix ssh bug: include the ~openssh~ package.
- fix ~eshell-open-here~ bug: open a new shell even when an existing shell is visible in a different frame
- implement ~gatsby:update-readme~

** License

GPL
