# this file is auto-generated by main.org, do not modify!

{
  description = "using flakes to manage emacs packages";

  inputs = {
    ligature = {
      url = "github:mickeynp/ligature.el";
      flake = false;
    };
    beacon = {
      url = "github:junyi-hou/beacon";
      flake = false;
    };
    org = {
      url = "github:yantar92/org/feature/org-fold-universal-core";
      flake = false;
    };
    org-appear = {
      url = "github:awth13/org-appear/feature/org-fold-support";
      flake = false;
    };
    flymake-childframe = {
      url = "github:junyi-hou/flymake-childframe";
      flake = false;
    };
    tsc-module = {
      url = "https://github.com/ubolonton/emacs-tree-sitter/releases/download/0.15.1/tsc-0.15.1.tar.gz";
      flake = false;
    };
    emacs-tree-sitter = {
      url = "github:ubolonton/emacs-tree-sitter";
      flake = false;
    };
    emacs-tree-sitter-langs = {
      url = "github:ubolonton/tree-sitter-langs";
      flake = false;
    };
    tree-sitter-fold = {
      url = "github:junyi-hou/tree-sitter-fold";
      flake = false;
    };
    tree-sitter-python-grammar = {
      url = "github:tree-sitter/tree-sitter-python";
      flake = false;
    };
    stata-mode = {
      url = "github:junyi-hou/stata-mode";
      flake = false;
    };
    tree-sitter-r-grammar = {
      url = "github:r-lib/tree-sitter-r";
      flake = false;
    };
    tree-sitter-nix-grammar = {
      url = "github:cstrahan/tree-sitter-nix";
      flake = false;
    };
  };

  outputs = { self, ... }@inputs: with inputs; {
    emacsConfig = { pkgs, lib, config, ... }: {
      home = {
        file = {
          ".emacs.d/etc" = {
            source = ./etc;
            recursive = true;
          };
          ".emacs.d/init.el".source = ./init.el;
        };
        sessionVariables = {
          EDITOR = "emacsclient -c";
          VISUAL = "emacsclient -c";
        };
      };
    };

    darwinCompatiblePatch = { pkgs, lib, config, ... }: with lib;
      let
        cfg = config.programs.emacs;
      in {
        options.programs.emacs = {
          enable = mkEnableOption "Emacs";

          package = mkOption {
            type = types.package;
            default = pkgs.emacs;
            defaultText = literalExample "pkgs.emacs";
            example = literalExample "pkgs.emacs25-nox";
            description = "The Emacs package to use.";
          };
        };
        config = mkIf cfg.enable {
          environment.systemPackages = [ cfg.package ];
        };
      };

    emacsPackage = emacsPkg: { pkgs, lib, config, ... }:
      let
        emacs = emacsPkg.pkgs.withPackages (epkgs: [
          epkgs.use-package
          epkgs.dash epkgs.s epkgs.f
          epkgs.gcmh
          epkgs.general
          epkgs.no-littering
          epkgs.visual-fill-column
          epkgs.alert
          epkgs.exec-path-from-shell
          epkgs.gruvbox-theme
          (emacsPkg.pkgs.trivialBuild {
            pname   = "ligature";
            version = "9999";
            src = ligature;
          })
          epkgs.highlight-indent-guides
          (emacsPkg.pkgs.trivialBuild {
            pname   = "beacon";
            version = "master";
            src = beacon;
          })
          epkgs.hl-todo
          epkgs.eldoc-box
          epkgs.evil
          epkgs.evil-surround
          epkgs.evil-nerd-commenter
          epkgs.expand-region
          epkgs.selectrum
          epkgs.prescient
          epkgs.selectrum-prescient
          epkgs.consult
          epkgs.marginalia
          (emacsPkg.pkgs.melpaBuild {
            pname = "org";
            ename = "org";
            version = "9999";
            recipe = builtins.toFile "recipe" ''
              (org :fetcher github
                    :repo "yantar92/org"
                    :branch "feature/org-fold-universal-core"
                    :files ("*.el" "lisp/*.el" "contrib/lisp/*.el"))
            '';
            src = org;
          })
          (emacsPkg.pkgs.trivialBuild {
            pname   = "org-appear";
            version = "master";
            src = org-appear;
          })
          epkgs.ob-async
          epkgs.flymake
          (emacsPkg.pkgs.trivialBuild {
            pname   = "flymake-childframe";
            version = "9999";
            src = flymake-childframe;
          })
          epkgs.company
          epkgs.company-prescient
          epkgs.yasnippet
          epkgs.eglot
          (
            let
              tsc = emacsPkg.pkgs.trivialBuild {
                pname = "tsc";
                version = "0.15.1";
                src = tsc-module;
                patches = [ ./tree-sitter-patches/tsc-do-not-download.patch ];
                installPhase = ''
                  runHook preInstall
              
                  LISPDIR=$out/share/emacs/site-lisp
                  install -d $LISPDIR
                  cp *.el *.elc *.dylib *.so $LISPDIR
              
                  runHook postInstall
                '';
              };
              tree-sitter = emacsPkg.pkgs.trivialBuild {
                pname = "tree-sitter";
                version = "9999";
                src = emacs-tree-sitter;
                packageRequires = [ tsc ];
                patches = [ ./tree-sitter-patches/tree-sitter-remove-buildin-tsc-dependency.patch ];
                buildPhase = ''
                  runHook preBuild
              
                  cp lisp/*.el ./
                  emacs -L . --batch -f batch-byte-compile *.el
              
                  runHook postBuild
                '';
              };
              tree-sitter-langs = emacsPkg.pkgs.trivialBuild {
                pname = "tree-sitter-langs";
                version = "9999";
                src = emacs-tree-sitter-langs;
                packageRequires = [ tree-sitter ];
                patches = [ ./tree-sitter-patches/tree-sitter-langs-do-not-require-bundled-grammars.patch ];
                installPhase = ''
                  runHook preInstall
              
                  LISPDIR=$out/share/emacs/site-lisp
                  install -d $LISPDIR
                  cp *.el *.elc $LISPDIR
                  cp -r queries $LISPDIR
              
                  runHook postInstall
                '';
              };
              tree-sitter-grammar = pkgs.stdenv.mkDerivation {
                name = "tree-sitter-grammars";
                srcs = [
                  tree-sitter-python-grammar
                  tree-sitter-r-grammar
                  tree-sitter-nix-grammar
                ];
                buildInputs = [ pkgs.nodejs pkgs.tree-sitter ];
                unpackPhase = ''
                  for i in $srcs; do
                      cp -r $i .
                  done
                  sourceRoot=.
                  chmod -R u+w -- "$sourceRoot"
                '';
                buildPhase = ''
                  mkdir -p $out/bin
                  export TREE_SITTER_DIR=$out
                  for d in *; do
                      if [ -d "$d" ]; then
                          cd "$d"
                          tree-sitter generate
                          tree-sitter test
                          cd ..
                      fi
                  done
                '';
                installPhase = ''
                  true
                '';
              };
            in
              pkgs.symlinkJoin {
                name = "tree-sitter-langs-with-grammars";
                paths = [
                  (tree-sitter-langs.overrideAttrs (oldAttrs: {
                    postPatch = oldAttrs.postPatch or "" + ''
                      substituteInPlace ./tree-sitter-langs-build.el \
                      --replace "tree-sitter-langs-grammar-dir tree-sitter-langs--dir"  "tree-sitter-langs-grammar-dir \"${tree-sitter-grammar}\""
                    '';
                  }))
                  tree-sitter-grammar
                  (emacsPkg.pkgs.trivialBuild {
                        pname   = "tree-sitter-fold";
                        version = "9999";
                        src = tree-sitter-fold;
                        packageRequires = [ tree-sitter ];
                      })
                ];
              }
          )
          epkgs.jupyter
          epkgs.ein
          epkgs.flyspell-correct
          epkgs.langtool
          epkgs.magit
          epkgs.magit-delta
          epkgs.forge
          epkgs.projectile
          epkgs.deadgrep
          epkgs.envrc
          epkgs.dired-rainbow epkgs.dired-collapse
          epkgs.helpful
          epkgs.aggressive-indent
          epkgs.easy-escape
          (emacsPkg.pkgs.trivialBuild {
            pname = "stata-mode";
            version = "9999";
            src = stata-mode;
          })
          epkgs.ess
          epkgs.nix-mode
          epkgs.markdown-mode
          epkgs.auctex
        ]);
      in
        {
          programs.emacs = {
            enable = true;
            package = emacs;
          };

          services.emacs = {
            enable = true;
            package = emacs;
          };
        };
  };
}
